### ISSUE TITLE
Hamiltonian problem types

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqPhysics.jl#1]
Make these auto-generate `PartitionedODEProblem`s.

**Comment by ChrisRackauckas** [comment]
Some more details. Hamiltonians can be written as `H(p,q)`. This then gives equations of motion 

`dp/dt = - dH/dq`
`dq/dt =   dH/dp`

Those equations of motion define a `PartitionedODEProblem`, where the partition has a set of ODEs for `p` and a set of ODEs for `q`. OrdinaryDiffEq.jl can natively handle this kind of `PartitionedODEProblem` and use things like Verlets, or it can (soon) transform it into a standard ODE for all of the other algorithms. So the actual solving can be handled by that.

What needs to be done is that the equations of motion need to be generated using differentiation tools. I.e., use something like ForwardDiff to define the equations of motion using a user defined `H(p,q)` function (for vectors `p` and `q`).

**Comment by Datseris** [comment]
I would like to try and solve this issue.
How do you envision the interface? 
` Hamiltonian(p,q) -> PartitionedODEProblem` etc?

I have had some experience with ForwardDiff for the DynamicalSystems package, so probably I can handle this... (don't be so sure though)

**Comment by ChrisRackauckas** [comment]
>How do you envision the interface?
ODEHamiltonian(p,q) -> PartitionedODEProblem etc?

Yes.

```julia
HamiltonianProblem(H,q0,p0,tspan)
```

Essentially what it will do is use ForwardDiff to make a function for dHdq and a function for dHdp, and build the `ODEProblem((dHdq,dHdp),(q0,p0),tspan)`. This output can then be directly solved by the symplectic solvers.

So the only "hard part" is the differentiation, which should just be differentiating a closure `ForwardDiff.derivative!((p)->H(p,q),...)`. And making tests of course. It actually should be pretty easy, but will be a nice convenience.

**Comment by Datseris** [comment]
Yeap okay, I will do that after I learn how all these new stuff works.

I will also make a method
`HamiltonianProblem(dHdq, dHdq, tspan)` in case the user can do the differentiation by themselves. I know its is identical to the `ODEProblem` but having the `Hamiltonian` name will be not only nice but intuitive as well.
