### ISSUE TITLE
having problems adding

### ISSUE THREAD

**Issue by francispoulin** [SciML/DiffEqPhysics.jl#20]
First, I want to apologize for being new to Julia and not knowing a lot of the basics.

Second, thanks for putting this together.  It looks great!

Third, unfortunately, when I try adding the packing using the standard approach (as I understand it) Iget an error.  See below for details.  Could someone help me figure out what I am doing wrong?

julia> Pkg.add("DiffEqPhysics")
ERROR: unknown package DiffEqPhysics
macro expansion at ./pkg/entry.jl:53 [inlined]
(::Base.Pkg.Entry.##1#3{String,Base.Pkg.Types.VersionSet})() at ./task.jl:335
Stacktrace:
 [1] sync_end() at ./task.jl:287
 [2] macro expansion at ./task.jl:303 [inlined]
 [3] add(::String, ::Base.Pkg.Types.VersionSet) at ./pkg/entry.jl:51
 [4] (::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at ./pkg/dir.jl:36
 [5] cd(::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at ./file.jl:70
 [6] #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{String,N} where N) at ./pkg/dir.jl:36
 [7] add(::String) at ./pkg/pkg.jl:117

**Comment by ChrisRackauckas** [comment]
Oh, this library isn't registered yet. Let me get it registered.

**Comment by francispoulin** [comment]
Ah, thank you.  I am looking forward to playing with the Outer-Solar-System notebook, whenever you get it registered.

**Comment by ChrisRackauckas** [comment]
In the meantime you can `Pkg.clone` to install it, but let me get it all up to snuff first.

**Comment by francispoulin** [comment]
I am in no rush so happy to wait until it is ready.  

I have been reading about Julia recently and very happy to learn more about what it does and hopefully use it in a class starting January!

**Comment by ChrisRackauckas** [comment]
It's registered now. I'll also add links to external modeling packages to the docs that may be of interest.

**Comment by francispoulin** [comment]
Thank you!  

I can confirm that after an "Pkg.update()" I was able to install the package.

Unfortunately, by the end it seemed to fail at something.  Any idea why that might be?

```

prob = NBodyProblem(V, M, pos, vel, tspan)
@time sol = solve(prob, Yoshida6(), dt=100);

AssertionError: dim * length(mass) == N

Stacktrace:
 [1] #NBodyProblem#1(::Array{Any,1}, ::Function, ::Function, ::Diagonal{Float64}, ::Array{Float64,1}, ::Array{Float64,1}, ::Tuple{Float64,Int64}) at /home/fpoulin/.julia/v0.6/DiffEqPhysics/src/nbody.jl:9
 [2] NBodyProblem(::Function, ::Diagonal{Float64}, ::Array{Float64,1}, ::Array{Float64,1}, ::Tuple{Float64,Int64}) at /home/fpoulin/.julia/v0.6/DiffEqPhysics/src/nbody.jl:5
 [3] include_string(::String, ::String) at ./loading.jl:515

```

**Comment by ChrisRackauckas** [comment]
What did you run?

**Comment by francispoulin** [comment]
Sorry, I should have said that I am running this notebook.

https://github.com/JuliaDiffEq/DiffEqTutorials.jl/blob/master/PhysicalModels/Outer-Solar-System.ipynb

**Comment by ChrisRackauckas** [comment]
I think that has to be updated due to https://github.com/JuliaDiffEq/DiffEqPhysics.jl/pull/18. @YingboMa are you available?

**Comment by ChrisRackauckas** [comment]
Bug in the implementation. I don't think the way of setting `u0` that is currently used will do well. Do you think 

```julia
prob = NBodyProblem(V, M, (x0,y0,z0), (vx0,vy0,vz0), tspan)
``

is good? I.e. dimension can be inferred from the size of the tuples, and the user needs to split the x,y,z themselves? If you think that's good I'll change the API for this.

Another thing is that the mass matrix should just be a vector:

```julia
M = [1.00000597682, 0.000954786104043, 0.000285583733151,
        0.0000437273164546, 0.0000517759138449, 1/1.3e8]
```

`T` and `V` need to be updated accordingly. I'll wait for a response on the API before changing up `T` and `V`.
