### ISSUE TITLE
package dependency errors?

### ISSUE THREAD

**Issue by SimonEnsemble** [SciML/DiffEqPhysics.jl#23]
Upon `Pkg.update()`

I got
```
INFO: Updating METADATA...
INFO: Updating Plots master...
INFO: Computing changes...
ERROR: AssertionError: verify_solution(sol, interface)
```
The solution resolved after I `Pkg.free("Plots")`. Then it said:
```
INFO: Freeing Plots
ERROR: resolve is unable to satisfy package requirements.
  The problem was detected when trying to find a feasible version
  for package DiffEqPhysics.
```

After I `Pkg.rm("DifferentialEquations")` it updated fine.

**Comment by ChrisRackauckas** [comment]
You can try updating with `ENV["JULIA_PKGRESOLVE_ACCURACY"]  = 5` and see if it updates. If not, either there's something out there which is upper bounding a dependency of DiffEq, or the package resolver is failing. The easiest way to handle it is to start anew by deleting your `.julia/v0.6` folder. It's the nuclear option but will work.

**Comment by ChrisRackauckas** [comment]
The package manager issues were resolved awhile ago. This should be fixed. Feel free to open another issue if it's not.
