### ISSUE TITLE
New package for N-body simulations

### ISSUE THREAD

**Issue by Mikhail-Vaganov** [SciML/DiffEqPhysics.jl#35]
## N-body package
@ChrisRackauckas, @dextorious I have made some notes regarding publishing a new package.
I suppose the project, which I am going to create, should be under JuliaDiffEq organization? In this case there might exist access rights issues for me.

1. Name variants for the package:
- NBodySimulator
- NBodyInteractions
- NBodyTools
- NBodyPhysics
- JuliaN (just for fun – using Julia in package name is usually a bad idea)

2. As I understood from the docs, I need to generate a new package without using Project.toml file, but instead implementing standard structure including REQUIRE file. I faced with some problems using `PkgDev` in v0.7 so, it seems like I will create the project structure manually.

3. Set up AppVeyor and Travis-ci testing for the N-body project.

4. Register/publish the package in METADATA.jl and create a pull request for that.

5. Tag and register v0.0.1 of the N-body package

## After creation of the package:
- Clean README.md of DiffEqPhysics (may be insert a link to the newly created package) .
- Refactor structs in the package for N-body simulation: at least highlight/separate objects for the MD simulations.
- Optimize the code of the created package, prepare documentation for its tools.
- Prepare the final GSoC blog with links, examples and pictures.

**Comment by Eggiverse** [comment]
I am curious about the state of this issue. It seems new package is already there now, and some structs like `MassBody` have been removed. 

However, README.md and some examples haven't been cleaned. Many features that are no longer there like `MassBody` are still exported.

Does this mean that this package is no longer maintained in favor of the NBodySimulator.jl ?

**Comment by ChrisRackauckas** [comment]
This package still has other stuff, like HamiltonianProblem, but yes it's not used for NBody problems anymore.
