### ISSUE TITLE
Confusing Notation

### ISSUE THREAD

**Issue by ChrisDeGrendele** [SciML/DiffEqPhysics.jl#50]
The following notation is confusing to me and most likely to potential users. 
```
function HamiltonianProblem{T}(H,p0,q0,tspan,p=nothing;kwargs...) where T
    if T == false
        if typeof(q0) <: Number
            dp = function (v,x,p,t)
                ForwardDiff.derivative(x->-H(v, x, p), x)
            end
            dq = function (v,x,p,t)
                ForwardDiff.derivative(v->H(v, x, p), v)
            end
```

A hamiltonian in physics, takes two parameters, p and q. In the above segment of code, we define the derivatives dp and dq using the following relation:

<img width="237" alt="Screen Shot 2020-04-16 at 3 41 28 PM" src="https://user-images.githubusercontent.com/35853499/79513461-beec5e00-7ff8-11ea-88b3-63447718f8bc.png">

In the derivative, we use H(v,x,p) where
v is "p" which usually corresponds to momentum, the initial values are passed as p0
x is "q" which usually corresponds to position, the initial values are passed as q0
and p is p, which has nothing to do with the p associated with a hamiltonian (it's params).

**Would there be any objections to me changing this a bit, so when a physicist looks at the code, it's obvious what is what?** Maybe this doesn't need to be addressed, but I think it would help. I'd love to hear anyone's thoughts. Thanks!

**Comment by ChrisRackauckas** [comment]
Yeah, that stuff can get renamed. Also, it would be nice to add ModelingToolkitization as an option, so tracing it with MTK to generate the analytical solutions instead of just the AD solutions. https://mtk.sciml.ai/dev/highlevel/#Direct-Tracing-1 for more details.
