### ISSUE TITLE
Extensions to standard force fields to control temperature

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqPhysics.jl#6]
When force field simulations are done in MD, many times the temperature needs to be controlled to make sure it's sampling from the right ensambles. Two methods for this are Nose-Hoover and Langivan.

The Nose-Hoover method modifies the resulting Hamiltonian:

https://en.wikipedia.org/wiki/Nos%C3%A9%E2%80%93Hoover_thermostat

This might be able to (?) be written directly as equations of motion modified by a parameter `s`.

Langivan equations add thermal stochasticity directly to the equations of motion by using an SDE instead of an ODE:

https://en.wikipedia.org/wiki/Langevin_dynamics

This gives an additive SDE which can be simulated using the tools in StochasticDiffEq.jl.

**Comment by ChrisRackauckas** [comment]
Note that a resource I am using is Allen and Tildesley's The Art of Molecular Dynamics.

**Comment by dpsanders** [comment]
Correction: Allen & Tildesley, *Computer Simulation of Liquids*
